package com.example.cocofit.recursos;

import android.database.sqlite.SQLiteDatabase;

import com.example.cocofit.AdminSQLiteOpenHelper;

public class BDaddCapitales {

    public static void insertCapitalesEuropa (SQLiteDatabase db) {
        //SQLiteDatabase db = admin.getWritableDatabase();
        for (int i = 0; i < capitales_europa.length; i++) {
            //db.execSQL("insert into capitales values (1,'España','Madrid','Europa',0)");
            db.execSQL("insert into capitales values (" + i + "," + "'" + paises_europa[i] + "','" + capitales_europa[i] + "','Europa',0);");
        }
    }

    public static String [] paises_europa = {" Rusia ",
            " Reino Unido ",
            " Turquía ",
            " Alemania ",
            " España ",
            " Ucrania ",
            " Italia ",
            " Francia  ",
            " Azerbaiyán ",
            " Rumania ",
            " Bielorrusia ",
            " Hungría ",
            " Polonia  ",
            " Austria  ",
            " Georgia ",
            " República Checa  ",
            " Bulgaria ",
            " Serbia ",
            " Bélgica  ",
            " Armenia ",
            " Kazajistán ",
            " Suecia ",
            " Países Bajos  ",
            " Letonia ",
            " Croacia ",
            " Macedonia del Norte ",
            " Moldavia ",
            " Grecia ",
            " Noruega ",
            " Finlandia  ",
            " Portugal  ",
            " Lituania  ",
            " Dinamarca ",
            " Albania ",
            " Irlanda ",
            " Eslovaquia ",
            " Estonia ",
            " Bosnia y Herzegovina ",
            " Eslovenia  ",
            " Montenegro ",
            " Suiza  ",
            " Islandia ",
            " Luxemburgo ",
            " Chipre ",
            " Andorra  ",
            " Malta ",
            " Liechtenstein ",
            " San Marino ",
            " Mónaco ",
            " Ciudad del Vaticano "};

    public static String [] capitales_europa = {" Moscú ",
            " Londres ",
            " Ankara ",
            " Berlín ",
            " Madrid ",
            " Kiev ",
            " Roma ",
            " París ",
            " Bakú ",
            " Bucarest ",
            " Minsk ",
            " Budapest ",
            " Varsovia ",
            " Viena ",
            " Tiflis ",
            " Praga ",
            " Sofía ",
            " Belgrado ",
            " Bruselas ",
            " Ereván ",
            " Nur-sultán ",
            " Estocolmo ",
            " Ámsterdam ",
            " Riga ",
            " Zagreb ",
            " Skopie ",
            " Chisináu ",
            " Atenas ",
            " Oslo ",
            " Helsinki ",
            " Lisboa ",
            " Vilna ",
            " Copenhague ",
            " Tirana ",
            " Dublín ",
            " Bratislava ",
            " Tallin ",
            " Sarajevo ",
            " Liubliana ",
            " Podgorica ",
            " Berna ",
            " Reikiavik ",
            " Luxemburgo (ciudad) ",
            " Nicosia ",
            " Andorra la Vieja ",
            " La Valeta ",
            " Vaduz ",
            " Ciudad de San Marino ",
            " Mónaco ",
            " Ciudad del Vaticano ",};
}
